# Generated by Django 3.1.1 on 2020-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawl', '0002_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('title', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('read_time', models.TextField()),
                ('link', models.TextField()),
                ('content', models.TextField()),
                ('last_request', models.DateTimeField()),
            ],
        ),
    ]
